- name: Create a temp dir for certificates
  file:
    path: /tmp/mongo
    state: directory
    mode: '0700'
    owner: root
    group: root

# Generate certificates
- name: Check if CA private certificate exists
  stat:
    path: /tmp/mongo/MongoCA.key
  register: ca_private_cert_exists

- name: Generate CA private key
  shell: "openssl genrsa -out /tmp/mongo/MongoCA.key 1024"
  when:
      - ca_private_cert_exists.stat.exists == false
  no_log: true

- name: Check if CA public certificate exists
  stat:
    path: /tmp/mongo/MongoCA.crt
  register: ca_public_cert_exists

- name: Copy template
  template:
    src: ca_rep_csr.conf.j2
    dest: /tmp/mongo
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Generate CA public key
  shell: "openssl req -x509 -new -extensions v3_ca -key /tmp/mongo/MongoCA.key -days 365 -out /tmp/mongo/MongoCA.crt < /tmp/mongo/ca_rep_csr.conf.j2"
  when:
    - ca_public_cert_exists.stat.exists == false

- name: fetch CA public certificate locally
  fetch:
    src: /tmp/mongo/{{ item }}
    dest: /tmp/mongo/
    # remote_src: yes
  with_items:
    - MongoCA.crt
    - MongoCA.key
